# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post_intro', models.CharField(max_length=150)),
                ('post_body', models.TextField()),
                ('post_img', models.URLField(blank=True, null=True)),
                ('post_category', models.CharField(choices=[('SOC', 'Sociedad'), ('DEP', 'Deportes'), ('CNC', 'Ciencia'), ('HST', 'Historia'), ('CLT', 'Cultura'), ('OTR', 'Otras')], default='OTR', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
