# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170318_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_short']},
        ),
    ]
