# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170318_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_published',
            field=models.CharField(choices=[('PUB', 'Published'), ('NPB', 'No_Published')], default='PUB', max_length=3),
        ),
    ]
